# Crie um Dockfile utilizando a imagem chuanwen/cowsay e defina um ENTRYPOINT para a execução do comando
FROM chuanwen/cowsay:latest
ENTRYPOINT ["/usr/games/cowsay"]

# Utilize o CMD para definir uma mensagem padrão
CMD [ "Hello World" ]
